 services:
  - type: web
    name: chatbot-web
    runtime: python
    buildCommand: "if [ -f build.sh ]; then ./build.sh; else ./build.bat; fi"   
    startCommand: "gunicorn chatbot_project.wsgi:application --workers 1 --threads 2 --timeout 180 --bind 0.0.0.0:10000"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    healthCheckPath: "/health/"

 databases:
  - name: chatbot-db
    plan: free