services:
  - type: web
    name: chatbot-web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn chatbot_project.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 180"
    envVars:
      - key: PORT
        value: "10000"  # Must match environment variable
      - key: DEBUG
        value: "False"
      - key: DB_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
    plan: free