# Generated by Django 5.2 on 2025-05-04 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
